### PR TITLE
ResourceStateAnnotation fix for clusterresource and kafkamanagement api groups

### LINKED ISSUE #510: Defaulting webhook adjustment for clusterresource API group
Add adjustments to defaulting webhooks for clusterresource API group to prevent panics.

### LINKED ISSUE #512: Defaulting webhook adjustment for kafkamanagement API group
Add adjustments to defaulting webhooks for kafkamanagement API group to prevent panics.

### PR DESCRIPTION
**Pull request by worryg0d**
Added adjustments to defaulting webhooks of **clusterresource** and **kafkamanagement** API group to prevent panics of nil pointer. For more information follow #495.

Added defaulting webhooks for resources in **clusterresource** API group:
- AWSEncryptionKey
- AWSSecurityGroupFirewallRule
- AWSVPCPeering
- AzureVNetPeering
- ClusterNetworkFirewallRule
- GCPVPCPeering

Added defaulting webhooks for resources in **kafkamanagement** API group:
- KafkaACL
- Mirror
- Topic
- KafkaUser

closes #510
closes #512

### CODE REVIEW

File: apis/clusterresources/v1beta1/awsencryptionkey_webhook.go [hunk 1]
```diff
@@ -36,6 +36,22 @@ func (aws *AWSEncryptionKey) SetupWebhookWithManager(mgr ctrl.Manager) error {
...
+//+kubebuilder:webhook:path=/mutate-clusterresources-instaclustr-com-v1beta1-awsencryptionkey,mutating=true,failurePolicy=fail,sideEffects=None,groups=clusterresources.instaclustr.com,resources=awsencryptionkeys,verbs=create;update,versions=v1beta1,name=mawsencryptionkey.kb.io,admissionReviewVersions=v1
+
+var _ webhook.Defaulter = &AWSEncryptionKey{}
+
+// Default implements webhook.Defaulter so a webhook will be registered for the type
+func (aws *AWSEncryptionKey) Default() {
+	awsencryptionkeylog.Info("default", "name", aws.Name)
+
+	if aws.GetAnnotations() == nil {
+		awsencryptionkeylog.Info("nil")
```
Comment (ribaraka) [inline apis/clusterresources/v1beta1/awsencryptionkey_webhook.go:48]: please remove it, or add a more informative message

File: apis/clusterresources/v1beta1/awssecuritygroupfirewallrule_webhook.go [hunk 2]
```diff
@@ -36,12 +36,26 @@ func (r *AWSSecurityGroupFirewallRule) SetupWebhookWithManager(mgr ctrl.Manager)
...
+		})
+	}
+}
+
 // TODO(user): change verbs to "verbs=create;update;delete" if you want to enable deletion validation.
 //+kubebuilder:webhook:path=/validate-clusterresources-instaclustr-com-v1beta1-awssecuritygroupfirewallrule,mutating=false,failurePolicy=fail,sideEffects=None,groups=clusterresources.instaclustr.com,resources=awssecuritygroupfirewallrules,verbs=create;update,versions=v1beta1,name=vawssecuritygroupfirewallrule.kb.io,admissionReviewVersions=v1
 
 var _ webhook.Validator = &AWSSecurityGroupFirewallRule{}
 
-// ValidateCreate implements webhook.Validator so a webhook will be registered for the type
```
Comment (RostislavPorohnya) [inline apis/clusterresources/v1beta1/awssecuritygroupfirewallrule_webhook.go:44]: Keep this comment

**Review by RostislavPorohnya — APPROVED** [review]

File: apis/clusterresources/v1beta1/awssecuritygroupfirewallrule_webhook.go (hunk 2 above)
Comment (worryg0d) [reply apis/clusterresources/v1beta1/awssecuritygroupfirewallrule_webhook.go]: Oops. Returned.

**Review by ribaraka — APPROVED** [review]

**Review by taaraora — APPROVED** [review]
