### PR TITLE
Issue-711, Avoiding cluster creation if cluster with provided name exists

### LINKED ISSUE #711: Avoid duplicate cluster creation
Minimize the risk of failure scenarios during cluster creation by implementing safeguards. Specifically, focus on situations where a create API is initiated but faces unexpected shutdown or errors in the k8s operator. This vulnerability can trigger an undesirable loop, resulting in the repeated execution of the create API request and the potential creation of numerous clusters.
I recommend using the [API call](https://instaclustr.redoc.ly/Current/tag/Account-Cluster-List-V2) to list all clusters in the account and verifying that the current cluster **name** doesn't already exist on the console

### PR DESCRIPTION
**Pull request by worryg0d**
closes #711

### CODE REVIEW

File: pkg/instaclustr/client.go [hunk 1]
```diff
@@ -2112,8 +2112,8 @@ func (c *Client) UpdatePostgreSQLDefaultUserPassword(id, password string) error
 	return nil
 }
 
-func (c *Client) ListClusters() ([]*models.ActiveClusters, error) {
-	url := c.serverHostname + ClustersEndpoint
+func (c *Client) ListClustersByName(name string) ([]*models.ActiveCluster, error) {
+	url := c.serverHostname + ClustersEndpoint + "?search=name:" + name
```
Comment (ribaraka) [inline pkg/instaclustr/client.go:2116]: please add app_type

**Review by testisnullus — APPROVED** [review]
