### PR TITLE
Fixes for the User CRDs

### LINKED ISSUE #532: [User CRD] New finilizer to a deleting resource
Our current logic ensures that when a user is attached to a cluster, a finalizer is added to the user to keep it from accidental removal and ensure healthy work. The flaw is when (accidentally) deleting a User with finalizers and you still want to work with the same user, there will be an issue to add the user yet to another cluster, k8s doesn’t allow adding new finalizers to deleting resources.

### PR DESCRIPTION
**Pull request by ribaraka**
- removed redundant finalizers in user functionality, which is set after each new cluster assignment.
- from now on we will use only one and only finalizer that is bound between a User CRD and the Secret.
- added a const containing a message for user deletion
- cleaned up a code
- moved the adding finalizers at the beginning of the reconcile func
- fixes along the way for some user controllers.
- Closes #532

### CODE REVIEW

**Review by testisnullus — APPROVED** [review]

File: controllers/clusterresources/helpers.go [hunk 1]
```diff
@@ -76,6 +76,4 @@ func getUserCreds(secret *k8sCore.Secret) (username, password string, err error)
 	return username[:len(username)-1], password[:len(password)-1], nil
 }
 
-func getDeletionUserFinalizer(clusterID string) string {
-	return models.DeletionUserFinalizer + clusterID
-}
+const msgDeleteUser = "If you want to delete the user, first remove the user from cluster specification"
```
Comment (worryg0d) [inline controllers/clusterresources/helpers.go:79]: Seems better to say:
```suggestion
const msgDeleteUser = "If you want to delete the user, first remove it from the clusters specifications"
```

File: controllers/kafkamanagement/kafkauser_controller.go [hunk 2]
```diff
@@ -414,26 +342,15 @@ func (r *KafkaUserReconciler) Reconcile(ctx context.Context, req ctrl.Request) (
 	if user.DeletionTimestamp != nil {
 		for clusterID, clusterEvent := range user.Status.ClustersEvents {
 			if clusterEvent == models.Created || clusterEvent == models.CreatingEvent || clusterEvent == models.UpdatingEvent || clusterEvent == models.UpdatedEvent {
-				l.Error(models.ErrUserStillExist, "please remove the user from the cluster specification",
+				l.Error(models.ErrUserStillExist, "If you want to delete the user, first remove the user from cluster specification",
 					"username", username, "cluster ID", clusterID)
 				r.EventRecorder.Event(user, models.Warning, models.DeletingEvent,
-					"The user is still attached to cluster, please remove the user from the cluster specification.")
+					"If you want to delete the user, first remove the user from cluster specification")
```
Comment (worryg0d) [inline controllers/kafkamanagement/kafkauser_controller.go:348]: Please use here `msgDeleteUser` as you do in other similar cases

Comment (ribaraka) [reply controllers/kafkamanagement/kafkauser_controller.go:348]: This const is in a different package. I'll think about what to do.

File: pkg/models/errors.go [hunk 3]
```diff
@@ -54,6 +54,6 @@ var (
 	ErrImmutableSecretRef                    = errors.New("secret reference is immutable")
 	ErrEmptySecretRef                        = errors.New("secretRef.name and secretRef.namespace should not be empty")
 	ErrMissingSecretKeys                     = errors.New("the secret is missing the correct keys for the user")
-	ErrUserStillExist                        = errors.New("the user is still attached to cluster")
+	ErrUserStillExist                        = errors.New("the user is still attached to cluster. If you want to delete the user, first remove the user from cluster specification")
```
[the remark this answers is not in the document]
Comment (ribaraka) [reply pkg/models/errors.go:57]: changed

File: controllers/clusterresources/helpers.go (hunk 1 above)
Comment (ribaraka) [reply controllers/clusterresources/helpers.go:79]: changed

File: controllers/kafkamanagement/kafkauser_controller.go [hunk 4]
```diff
@@ -87,19 +87,40 @@ func (r *KafkaUserReconciler) Reconcile(ctx context.Context, req ctrl.Request) (
...
-		)
+	if err != nil {
+		l.Error(err, "Cannot get secret for kafka user.", "request", req)
+		r.EventRecorder.Eventf(user, models.Warning, models.FetchFailed,
+			"Fetch user credentials secret is failed. Reason: %v", err)
 
 		return models.ReconcileRequeue, nil
 	}
 
+	if controllerutil.AddFinalizer(secret, user.GetDeletionFinalizer()) {
```
Comment (OleksiienkoMykyta) [inline controllers/kafkamanagement/kafkauser_controller.go:98]: I think it would be better to add finalizer after getting creds

**Review by OleksiienkoMykyta — APPROVED** [review]

File: controllers/kafkamanagement/kafkauser_controller.go (hunk 4 above)
Comment (ribaraka) [reply controllers/kafkamanagement/kafkauser_controller.go:108]: good idea! fixed

**Review by taaraora — APPROVED** [review]
